---
- hosts: 172.31.11.172
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: copy static files into ansible nodes
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfiles

  - name: install webserver
    apt:
     name: apache2
     state: present