- name: grant tomcat ownership  on tomcat
  excute: sudo chown -R tomcat:tomcat /opt/tomcat/

- name: change to excute permission on use leave on bin folder
  excute: sudo chmod -R u+x /opt/tomcat/bin